**

!README.md
!LICENSE

!python
!python/**

!rust
!rust/**

!proto
!proto/**

!lossy-spec-dec
!lossy-spec-dec/**

**/__pycache__
**/__pycache__/**
*.py[cod]

lossy-spec-dec/runs
lossy-spec-dec/runs/**
lossy-spec-dec/images
lossy-spec-dec/images/**
